baseurl = "https://yimiyisu.club"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
title = "一米一粟的技术博客"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Nice to meet you here"
subtitle = "Tracking my ideas of coding and life"
#logo = ""
favicon = ""
dateFormat = "January 2, 2006"
commit = false
#rss = true
baiduKey = ""
#comments = false
#sharebutton = true
#algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "yimiyisu.club"
#errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"

[[Params.bigimg]]
src = "/images/gohugo-default-sample-hero-image.jpg"
desc = ""


[Author]
  name = "一米一粟"
  website = "https://yimiyisu.club"
  github = "setNull"
  linkedin = "jie-wang-b10ab976"
  email = "wangjie2011cs@gmail.com"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Machine Learning"
    url = "categories/machine-learning"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Programming"
    url = "categories/programming"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "DevOps"
    url = "categories/devops"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Effective"
    url = "categories/effective"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Codes"
    name = "Codes"
    weight = 2

[[menu.main]]
    parent = "Codes"
    name = "face_recognition"
    url = "https://github.com/ageitgey/face_recognition"
    weight = 2


[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
