baseurl = "https://blog.yimiyisu.club/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
title = "一米一粟的技术博客"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Nice to meet you here"
subtitle = "Tracking my ideas of coding and life"
#logo = ""
favicon = ""
dateFormat = "January 2, 2006"
#rss = true
baiduKey = ""
comments = true
sharebutton = true
algolia = "4bfe9116489df902f720b8c4d468391e" # API key
description = "blog.yimiyisu.club"

[[Params.bigimg]]
src = "/images/gohugo-default-sample-hero-image.jpg"
desc = ""


[Author]
  name = "一米一粟"
  website = "https://blog.yimiyisu.club/"
  github = "setNull"
  linkedin = "jie-wang-b10ab976"
  email = "wangjie2011cs@gmail.com"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "ML"
    url = "categories/machine-learning"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Programming"
    url = "categories/programming"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "DevOps"
    url = "categories/devops"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Effective"
    url = "categories/effective"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Algorithm"
    url = "categories/algoritm"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Codes"
    name = "Open Source"
    weight = 2

[[menu.main]]
    parent = "Codes"
    name = "Face_Recognition"
    url = "https://github.com/ageitgey/face_recognition"
    weight = 2

[[menu.main]]
    parent = "Codes"
    name = "FaceNet"
    url = "https://github.com/davidsandberg/facenet"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
